from suds.client import Client
import json

string_json = '{"Nama_Lengkap":"DICKY FIRMANSYAH","Jenis_Kelamin":"","Kewarganegaraan":"","Negara":"","Tempat_Lahir":"","Tanggal_Lahir":"","Nama_Ibu":"","Jenis_Identitas":"KT","Tanggal_Terbit_ID":"","Tanggal_Kadaluarsa_ID":"","No_Identitas":"1234567891234567","Pendidikan":"ZZ","Agama":"","Status_Menikah":"","Hobi":"HOBI","Address_ID":"","KodePos_ID":"","RT_ID":"","RW_ID":"","Kel_ID":"","Kec_ID":"","Kota_ID":"","Propinsi_ID":"","Alamat_Domisili":"","KodePos_Domisili":"","RT_Domisili":"","RW_Domisili":"","Kel_Domisili":"","Kec_Domisili":"","Kota_Domisili":"","Propinsi_Domisili":"","Telepon_Nasabah":"","Fax_Nasabah":"","HP_Nasabah":"","Email_Nasabah":"","Jenis_Pekerjaan":"BUMN","Nama_Kantor":"BRI","Bidang_Pekerjaan":"IT","Tahun_LamaKerja":"5","Bulan_LamaKerja":"01","Jabatan":"STAFF","NPWP":"","Alamat_Kantor":"ALAMAT","KodePos_Kantor":"16425","RT_Kantor":"","RW_Kantor":"","Kel_Kantor":"KUKUSAN KEL","Kec_Kantor":"BEJI","Kota_Kantor":"DEPOK KOT.","Propinsi_Kantor":"JAWA BARAT","TelpNo_Kantor":"","Fax_Kantor":"","Alamat_Surat":"1","Penghasilan_Perbulan":"G1","Kepemilikan_KKBRI":"Y","Transaksi_Harian":"N1","Sumber_Penghasilan":"00011","Tipe_Produk":"SU","QQ_Junio":"","Tujuan_Buka_AccNonDeposit":"T1","Mata_Uang_AccNonDeposit":"IDR","Jenis_Kartu_Accnt":"PRIV","Rek_Koran_Alamat":"","Mobile_Banking":"ON","Internet_Banking":"","Phone_Banking":"","SMS_Notifikasi":"","Limit_Notifikasi":"","Alamat_Email_Notifikasi":"","NomorHP_Fasilitas":"","Setoran":"1000000","Setoran_Terbilang":"SATU JUTA RUPIAH","Mata_Uang_Deposito":"","Pokok_Deposito":"","Pokok_Deposito_Terbilang":"","Jangka_Waktu_Deposito":"","Perpanjangan_Deposito":"","Pembayaran_Bunga_Deposito":"","Nama_Bank_Deposito_Intrs":"","Atas_Nama_Deposito_Intrs":"","Nomor_Rekening_Deposito_Intrs":"","Is_AddrIdSameAddrDom":"ON","Is_Existing_Customer":"N","Nama_Bank_NonBRI1":"","Nama_Bank_NonBRI2":"","Jenis_Rekening_NonBRI1":"","Jenis_Rekening_NonBRI2":"","Penerbit_CCNonBRI1":"","Penerbit_CCNonBRI2":"","Tipe_CCNonBRI1":"","Tipe_CCNonBRI2":"","Punya_CCBRI":"","Term_and_Condition":"1","Customer_Agreement":"1","Mata_Uang_Setoran":"IDR","Setoran_Deposito":"","Referral":"","Nama_PE":"","Code_PE":"","SID":"","Sub_rek_efek":"","Email_Nasabah_Rdn":"","Nama_Uker":"3251;UNIT JAGAKARSA CINERE","link_edit":"EFORM_SIMPEDES\/EDIT_FORM_DATA_PRIBADI_SIMPEDES_NEW"}'

url="http://10.35.65.18/formless/public/transactionws?wsdl"
client = Client(url)

result = client.service.sendTransaction(transactionObject=string_json)
print(result)
